Repository voxpupuli/beaker, pull requests merged in 2021-12, with the labels that each got.

#1719 Initial EL9 support
  lib/beaker/host_prebuilt_steps.rb
Labels: enhancement

#1722 Arch Linux: install net-tools and openssh
  lib/beaker/host_prebuilt_steps.rb
Labels: bug

#1723 Release 4.32.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog
