Repository voxpupuli/beaker, pull requests merged in 2023-04, with the labels that each got.

#1799 Release 4.40.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog

#1804 Switch to voxpupuli-rubocop
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  beaker.gemspec
Labels: enhancement

#1735 Support an extension to tmpfile
  lib/beaker/host/aix/file.rb
  lib/beaker/host/pswindows/file.rb
  lib/beaker/host/unix/file.rb
  lib/beaker/host/windows/file.rb
Labels: bug

#1808 Use systemctl to restart SSH on EL9
  lib/beaker/host/unix/exec.rb
Labels: bug

#1809 Release 5.2.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog
