Repository voxpupuli/beaker, pull requests merged in 2023-03, with the labels that each got.

#1764 (maint) Removes open_uri_redirections
  beaker.gemspec
  lib/beaker/dsl/helpers/web_helpers.rb
  spec/beaker/dsl/helpers/web_helpers_spec.rb
Labels: backwards-incompatible

#1769 Drop deprecated methods
  acceptance/tests/base/dsl/helpers/host_helpers/deploy_package_repo_test.rb
  acceptance/tests/base/dsl/helpers/host_helpers/run_cron_on_test.rb
  acceptance/tests/base/host/packages_unix.rb
  docs/how_to/debug_beaker_tests.md
  docs/how_to/the_beaker_dsl.md
  lib/beaker/dsl/assertions.rb
  lib/beaker/dsl/helpers/host_helpers.rb
  lib/beaker/host/mac/pkg.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/logger.rb
  lib/beaker/test_case.rb
  spec/beaker/dsl/helpers/host_helpers_spec.rb
  spec/beaker/dsl/structure_spec.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/host_prebuilt_steps_spec.rb
Labels: backwards-incompatible

#1731 Remove add-el-extras, passenger, proxy_config, disable_iptables and clean up code
  Rakefile
  acceptance/fixtures/module/spec/spec_helper_acceptance.rb
  acceptance/lib/helpers/test_helper.rb
  acceptance/tests/base/dsl/helpers/configuration_test.rb
  acceptance/tests/base/host/host_test.rb
  acceptance/tests/load_path_bootstrap.rb
  docs/concepts/argument_processing_and_precedence.md
  lib/beaker.rb
  lib/beaker/host.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/hypervisor.rb
  lib/beaker/options/command_line_parser.rb
  lib/beaker/options/presets.rb
  lib/beaker/subcommand.rb
  spec/beaker/host_prebuilt_steps_spec.rb
  spec/beaker/host_spec.rb
  spec/beaker/hypervisor/hypervisor_spec.rb
  spec/beaker/options/command_line_parser_spec.rb
  spec/beaker/options/hosts_file_parser_spec.rb
  spec/beaker/options/options_file_parser_spec.rb
  spec/beaker/options/parser_spec.rb
  spec/beaker/options/validator_spec.rb
  spec/beaker/subcommand_spec.rb
Labels: backwards-incompatible

#1762 Test on Ruby 3.2
  .github/workflows/test.yml
  acceptance/tests/base/host/host_test.rb
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
Labels: enhancement

#1794 Release 5.0.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog
