Repository voxpupuli/beaker, pull requests merged in 2023-11, with the labels that each got.

#1828 [PA-5938] Add support for debian & amazon linux in beaker 4.x
  .rubocop_todo.yml
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/file.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/perf.rb
  lib/beaker/platform.rb
  spec/beaker/host/unix/file_spec.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/host_prebuilt_steps_spec.rb
  spec/beaker/platform_spec.rb
  spec/helpers.rb
Labels: enhancement

#1832 Use DNF for Amazon Linux 2023
  lib/beaker/host/unix/pkg.rb
Labels: bug

#1835 Use DNF for Fedora, newer Enterprise Linux
  lib/beaker/host/unix/pkg.rb
  spec/beaker/host/unix/pkg_spec.rb
Labels: bug

#1836 voxpupuli-rubocop: Require 2.x
  beaker.gemspec
Labels: skip-changelog

#1837 Release 5.6.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog
