Repository voxpupuli/beaker, pull requests merged in 2024-05, with the labels that each got.

#1863 Add extension parameter to parent tmpfile method signature
  lib/beaker/host.rb
Labels: bug

#1865 CHANGELOG.md: Fix typo in PR link
  CHANGELOG.md
Labels: skip-changelog

#1866 Drop EoL F5 support
  acceptance/tests/base/host_prebuilt_steps/ssh_environment_test.rb
  lib/beaker/host/unix.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/platform.rb
  spec/beaker/host_prebuilt_steps_spec.rb
Labels: backwards-incompatible

#1867 Drop EoL cumulus support
  .rubocop_todo.yml
  acceptance/tests/base/host/packages.rb
  docs/concepts/argument_processing_and_precedence.md
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/file.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/options/command_line_parser.rb
  lib/beaker/perf.rb
  lib/beaker/platform.rb
  spec/beaker/host/unix/file_spec.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/host_prebuilt_steps_spec.rb
  spec/helpers.rb
Labels: backwards-incompatible

#1869 Drop EoL huaweios support
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/file.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/platform.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/helpers.rb
Labels: backwards-incompatible

#1870 Drop EoL EL4 support
  lib/beaker/host/unix/pkg.rb
  lib/beaker/options/parser.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/options/parser_spec.rb
Labels: backwards-incompatible

#1874 Drop EoL Arista EOS support
  docs/how_to/hosts/eos.md
  lib/beaker/host.rb
  lib/beaker/host/eos.rb
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/perf.rb
  lib/beaker/platform.rb
  spec/beaker/host/eos_spec.rb
  spec/beaker/host/unix/file_spec.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/host_prebuilt_steps_spec.rb
  spec/helpers.rb
Labels: backwards-incompatible

#1872 Drop EoL cisco support
  .rubocop_todo.yml
  docs/how_to/hosts/cisco.md
  lib/beaker/command.rb
  lib/beaker/host.rb
  lib/beaker/host/cisco.rb
  lib/beaker/host/unix/file.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/platform.rb
  spec/beaker/host/cisco_spec.rb
  spec/beaker/host/unix/exec_spec.rb
  spec/beaker/host/unix/file_spec.rb
  spec/beaker/host/unix/pkg_spec.rb
  spec/beaker/host/unix_spec.rb
  spec/beaker/host_prebuilt_steps_spec.rb
Labels: backwards-incompatible

#1873 Drop Fedora < 22 support
  acceptance/fixtures/module/spec/acceptance/nodesets/fedora-18-x64.yml
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-20-i386.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-20-x86_64.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-21-i386.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-21-x86_64.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-22-i386.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-22-x86_64.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-23-i386.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-23-x86_64.repo
  acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-24-x86_64.repo
  lib/beaker/host/unix/exec.rb
  lib/beaker/host/unix/pkg.rb
  lib/beaker/host_prebuilt_steps.rb
  spec/beaker/host_prebuilt_steps_spec.rb
  spec/helpers.rb
Labels: backwards-incompatible

#1875 drop validate_setup method
  .rubocop_todo.yml
  lib/beaker/host/unix.rb
  lib/beaker/network_manager.rb
Labels: backwards-incompatible

#1876 Drop EoL netscaler support
  lib/beaker/host/unix.rb
  lib/beaker/host_prebuilt_steps.rb
  lib/beaker/platform.rb
Labels: backwards-incompatible

#1871 Drop support for EoL Debian/Ubuntu versions
  lib/beaker/platform.rb
  spec/beaker/host/unix/file_spec.rb
  spec/beaker/platform_spec.rb
Labels: backwards-incompatible

#1868 drop sys-v leftovers; assume systemctl is available for unknown platforms
  .rubocop_todo.yml
  lib/beaker/host/unix/exec.rb
  spec/beaker/host/unix/exec_spec.rb
  spec/helpers.rb
Labels: backwards-incompatible

#1883 non-systemd SLES: Readd support for restarting sshd via `rcsshd`
  lib/beaker/host/unix/exec.rb
Labels: skip-changelog

#1884 Add package logic for Amazon Linux 2
  lib/beaker/host/unix/pkg.rb
  spec/beaker/host/unix/pkg_spec.rb
Labels: enhancement
