Repository voxpupuli/beaker, pull requests merged in 2024-02, with the labels that each got.

#1847 Add Ubuntu 24.04 noble codename
  lib/beaker/platform.rb
  spec/beaker/platform_spec.rb
Labels: enhancement

#1848 Release 5.7.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog

#1849 CLI: Fix typo: opton->option
  docs/concepts/argument_processing_and_precedence.md
  lib/beaker/options/command_line_parser.rb
Labels: bug
