Repository voxpupuli/beaker, pull requests merged in 2025-05, with the labels that each got.

#1916 Fix some doc issues
  docs/tutorials/installation.md
  docs/tutorials/quick_start_rake_tasks.md
Labels: enhancement

#1915 Fix macOS package installation when DMG content differs from filename
  .rubocop_todo.yml
  lib/beaker/host/mac/pkg.rb
  spec/beaker/host/mac/pkg_spec.rb
Labels: bug

#1921 pin excon to 1.2.5
  beaker.gemspec
Labels: bug

#1925 Revert "pin excon to 1.2.5"
  beaker.gemspec
Labels: skip-changelog

#1918 fakefs: Allow 3.x
  beaker.gemspec
Labels: enhancement

#1919 voxpupuli-rubocop: Update 3.0.0->3.1.0
  .rubocop_todo.yml
  beaker.gemspec
  lib/beaker/cli.rb
  lib/beaker/dsl/structure.rb
  lib/beaker/logger_junit.rb
  lib/beaker/ssh_connection.rb
  lib/beaker/test_suite_result.rb
Labels: enhancement

#1927 Release 6.7.0
  CHANGELOG.md
  lib/beaker/version.rb
Labels: skip-changelog
